### PR TITLE
Collect by

### PR DESCRIPTION
**Pull request by ahmedash95**
actually i see this method in Ruby .. and it's really awesome to add it to collections .. 

collectBy method is the GroupBy based on conditions instead of array key 

for example : 

```php
$emails = collect([
		["name" => "Ahmed Ashraf" , "email" => "ahmed@speakol.com"],
		["name" => "Mahmoud Ashraf" , "email" => "mahmoud@gmail.com"],
		["name" => "Mohamed Fergany" , "email" => "fergany@speakol.com"],
		["name" => "Mohamed Tayee" , "email" => "me@tayee.com"],
]);
```

to split the array and get all @speakol members

```php
$emails->collectBy(function($row){
	return strpos($row['email'],'@speakol') !== false;
})
```

the result : 

```
array(
   [
		["name" => "Ahmed Ashraf" , "email" => "ahmed@speakol.com"],
		["name" => "Mohamed Fergany" , "email" => "fergany@speakol.com"],
    ],
    [
		["name" => "Mahmoud Ashraf" , "email" => "mahmoud@gmail.com"],
		["name" => "Mohamed Tayee" , "email" => "me@tayee.com"],
    ]
);
```

### CODE REVIEW

**Comment by freekmurze** [comment]
Hi, 

thanks for contributing.

I like the functionality, but not the implementation.

Could you avoid using passing an array by reference?

Also (but this is a minor remark) Style CI doesn't seem to agree with your code.

**Comment by ahmedash95** [comment]
@freekmurze thanks for advice .. based on Adam Wathan's article "Customizing Keys When Mapping" i used collection reduce to avoid passing array as a reference .

**Comment by freekmurze** [comment]
Correct me if I'm wrong, but it doesn't seem that this function does a group by operation. It's more a filter that puts the elements of which the callback passes in the first group, and everything that doesn't in the second group. Am I right on that?

**Comment by ahmedash95** [comment]
@freekmurze you are right .. it's something like a filter . but what makes me called it group by is ruby array's function group_by takes a callback argument ..

**Comment by freekmurze** [comment]
At this time, I'm not going to pull this in. Even though Ruby uses this, it doesn't feel right to me.

You're of course free to use your own macro in your own projects 😄

**Comment by ahmedash95** [comment]
@freekmurze  thanks for reply .. but if you could tell me why you don't feel right about this ?

**Comment by ahmedash95** [comment]
@freekmurze i'm agree with you .. and i could make a PR for something like that but let me give you an example for using this .. i'm working on website validation tool .. the img validation rule check if img element has tag "Alt" and it must not be empty .. so i get all img elements from dom then i use collect by for return two arrays the first one is the passes elements and the second array is the elements without alt or with alt but empty . is this make it sense for you ?

**Comment by freekmurze** [comment]
For now, we've decide not to accept this functionality. I do appreciated your efforts though.

**Pull request closed without merging**
