### PR TITLE
pluckMany dotted key support

### PR DESCRIPTION
**Pull request by sfinktah**
To bring `pluckMany` inline with various other `pluck` implementations, including `Collections::pluck` (`Arr::pluck`), this allows the specification of dotted keys.

e.g.,

```php
$ar = collect($chunk)
    ->pluckMany(['id', 'handle', 'variants.edges.0.node.sku', 'spaghetti']);
```

### CODE REVIEW

**Comment by sfinktah** [comment]
@spatie-bot Dear unhelpful bot, I cannot control the reactions of  your masters.

**Comment by freekmurze** [comment]
Could you document this?

**Comment by sfinktah** [comment]
Dear human :)

How would you like it documented, it's how lodash (though not underscore) behaves when a string key is specified to `_.map` 

It's also how Collection::pluck operates.  If you would permit me a slight rudeness, you should be documenting why your pluckMany **doesn't** operated on dotted values.

```php
    public static function pluck($array, $value, $key = null)
    {
        $results = [];

        [$value, $key] = static::explodePluckParameters($value, $key);

        foreach ($array as $item) {
            $itemValue = data_get($item, $value);
```

```php
    function data_get($target, $key, $default = null)
    {
        if (is_null($key)) {
            return $target;
        }

        $key = is_array($key) ? $key : explode('.', $key);

        foreach ($key as $i => $segment) {
            unset($key[$i]);

            if (is_null($segment)) {
                return $target;
            }

            if ($segment === '*') {
                if ($target instanceof Collection) {
                    $target = $target->all();
                } elseif (! is_iterable($target)) {
                    return value($default);
                }

                $result = [];

                foreach ($target as $item) {
                    $result[] = data_get($item, $key);
                }

                return in_array('*', $key) ? Arr::collapse($result) : $result;
            }
// ...
```

**Comment by lazerg** [comment]
Great macro. When will be merged 👀

**Comment by freekmurze** [comment]
Thanks!

**Pull request merged**
