### PR TITLE
Add Transpose Macro

### PR DESCRIPTION
**Pull request by sixlive**
- Add transpose macro
- Add test for transpose macro

Adding the transpose maco based on a [post](https://adamwathan.me/2016/04/06/cleaning-up-form-input-with-transpose/) from Adam Wathan's blog. I've found this to be pretty handy and end up adding it to most projects.

### CODE REVIEW

**Comment by freekmurze** [comment]
Hi, thank you for this!

Could you also update the readme?

I'll take care of StyleCI after merging

**Comment by sixlive** [comment]
Whoops! Sure thing!

**Comment by freekmurze** [comment]
Merge conflicts, rebase to master, when you're working on it again.

**Comment by sixlive** [comment]
Cool, thanks for the heads up

**Comment by freekmurze** [comment]
Great work, thanks!

**Pull request merged**
