### PR TITLE
Added customization options for `groupByModel`

### PR DESCRIPTION
**Pull request by mdrost**
Just to be consistent with `sectionBy` I packed more features in fewer lines of code.

### CODE REVIEW

**Comment by mdrost** [comment]
ping @sebastiandedeyne

**Comment by sebastiandedeyne** [comment]
Sorry missed this! Gonna spend some time on upgrading this package to Laravel 5.5 this week, I'll handle this PR while I'm at it.

**Comment by sebastiandedeyne** [comment]
Hi!

I'm just gonna merge this in and go through the entire package for some maintenance. At first sight everything looks good, I'll keep you posted here when I'm done.

**Comment by sebastiandedeyne** [comment]
In the next major version of this package (should be released next week), by default the result won't have any keys but will be a two-element array (this is useful for `list()` & `eachSpread`/`mapSpread`)

Keys can still be provided if you pass them to the method.

Thanks for your contributions here!

**Comment by mdrost** [comment]
I would see this pull request in current major version as it is backward compatible. If in next major version the results will be two-element arrays then I suggest to rethink the order of parameters — maybe `$preserveKeys` as second parameter before `$modelKey` and `$itemsKey`?

**Comment by sebastiandedeyne** [comment]
Released in `2.7.0`!

I agree with the parameter order for the next version, gonna change that 👌

**Pull request merged**
