### PR TITLE
Adding two macros, After and Before

### PR DESCRIPTION
**Pull request by fernandobandeira**
Added Tests and Examples, these macros can be useful for layouts when you may have a next post / newer post, and things like that =)

### CODE REVIEW

**Comment by sebastiandedeyne** [comment]
Wouldn't `before` and `after` make more sense?

And maybe allow a second `$fallback` argument?

**Comment by fernandobandeira** [comment]
Yes, probably, will update the PR 😄

**Comment by RikSomers** [comment]
In my opinion returning `null` if the next or previous element doe not exist would be better. Any reason you chose false? @fernandobandeira

**Comment by fernandobandeira** [comment]
I created these two functions based on the search function of the core Collection and that function also returns false if the result is not found, originally these functions would be to search the next/previous element inside the collection and false would mean that it failed.

It still does that however with the new fallback returning null makes more sense now, i modified the PR...

**Comment by RikSomers** [comment]
A right. That makes sense. Was just wondering :)

**Comment by sebastiandedeyne** [comment]
One more thing, could you ensure (and add a test) that the methods work when providing a callable, like `search`?

See the third example here: https://laravel.com/docs/master/collections#method-search

**Comment by fernandobandeira** [comment]
Sure, added it...

**Comment by sebastiandedeyne** [comment]
Thanks! I'll review and merge the final code tomorrow :)

**Comment by sebastiandedeyne** [comment]
Thanks for the contribution! Released in version 2.1.0.

https://github.com/spatie/laravel-collection-macros/releases/tag/2.1.0

**Pull request merged**
