### PR TITLE
Allow to transpose empty collection.

### PR DESCRIPTION
**Pull request by mdrost**

### CODE REVIEW

**Comment by mdrost** [comment]
Consider just pull https://github.com/spatie/laravel-collection-macros/pull/91

**Comment by sebastiandedeyne** [comment]
Apparently some conflicts with your other PR. Could you do a quick resolve? Then I'll merge and tag a new release :)

**Comment by mdrost** [comment]
Done.  
Btw. according to https://lubomir.github.io/en/2016-04-03-TIL-overlapping-pull-requests.html it should be able to be merged because pull request https://github.com/spatie/laravel-collection-macros/pull/90 contains commits from this pull request.

**Comment by mdrost** [comment]
Now it's empty pull request :D

**Comment by sebastiandedeyne** [comment]
Thanks!

**Pull request merged**
